### ISSUE TITLE
City2 is sometimes numeric

### ISSUE THREAD

**Issue by thedivtagguy** [Vonter/india-aviation-traffic#1]
The `city2` variable might now always be a city name and is sometimes a number ([in this dataset](https://flatgithub.com/Vonter/india-aviation-traffic?filename=aggregated%2Fdomestic%2Fcity.csv&sha=d184b5748ea3b32137b33cc95fbca105fba4c846&stickyColumnName=City1)) 

![image](https://github.com/user-attachments/assets/9cd1219a-01f5-408f-9c5c-e29f9e00188e)

Problematic pairings and how many times they occur:
|city1          |  n|
|:--------------|--:|
|CHENNAI        | 22|
|DELHI          | 14|
|PUNE           | 14|
|HYDERABAD      | 12|
|SRINAGAR       | 12|
|VISAKHAPATNAM  | 12|
|LUCKNOW        |  9|
|RAIPUR         |  9|
|TRIVANDRUM     |  9|
|INDORE         |  8|
|JAIPUR         |  8|
|MUMBAI         |  8|
|GUWAHATI       |  7|
|PATNA          |  7|
|VARANASI       |  7|
|AGARTALA       |  6|
|BAGDOGRA       |  6|
|GOA            |  6|
|IMPHAL         |  6|
|KOCHI          |  6|
|KOLKATA        |  6|
|NAGPUR         |  6|
|CHANDIGARH     |  5|
|COIMBATORE     |  5|
|MANGALORE      |  5|
|PORT BLAIR     |  5|
|BENGALURU      |  4|
|JABALPUR       |  4|
|RANCHI         |  4|
|TIRUPATI       |  4|
|VIJAYAWADA     |  4|
|AURANGABAD     |  3|
|DIBRUGARH      |  3|
|DIMAPUR        |  3|
|JODHPUR        |  3|
|JORHAT         |  3|
|MADURAI        |  3|
|RAJKOT         |  3|
|UDAIPUR        |  3|
|ALLAHABAD      |  2|
|BELGAUM        |  2|
|DEHRA DUN      |  2|
|GWALIOR        |  2|
|JAMMU          |  2|
|KOZHIKODE      |  2|
|LEH            |  2|
|PORBANDAR      |  2|
|RAJAHMUNDRY    |  2|
|SILCHAR        |  2|
|BHOPAL         |  1|
|CUDDAPAH       |  1|
|DHARAMSALA     |  1|
|DIU            |  1|
|DURGAPUR       |  1|
|GAYA           |  1|
|HUBLI          |  1|
|JAMNAGAR       |  1|
|KHAJURAHO      |  1|
|KULLU          |  1|
|LILABARI       |  1|
|PANTNAGAR      |  1|
|PUDUCHERRY     |  1|
|SHILLONG       |  1|
|SURAT          |  1|
|TEZPUR         |  1|
|TIRUCHIRAPALLY |  1|
|TUTICORIN      |  1|

**Comment by Vonter** [comment]
Thank you for the error report @thedivtagguy

The August 2015 report published by DGCA appears to be an edge case as it does not include an initial `Sl. No.` column as the other reports include. The data processing for this has been fixed by handling it as an edge case as part of https://github.com/Vonter/india-aviation-traffic/pull/2
